// <auto-generated />
using System;
using DreamDays.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamDays.Migrations
{
    [DbContext(typeof(DreamDaysDbContext))]
    [Migration("20250510020953_FixDynamicSeedData")]
    partial class FixDynamicSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+ChecklistItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChecklistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Book Venue",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 2,
                            Deadline = new DateTime(2024, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Send Invitations",
                            IsCompleted = true
                        },
                        new
                        {
                            Id = 3,
                            Deadline = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Choose Caterer",
                            IsCompleted = false
                        });
                });

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+CoupleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partner1Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partner2Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WeddingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Couples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.jane@example.com",
                            Partner1Name = "John",
                            Partner2Name = "Jane",
                            WeddingDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Email = "alice.bob@example.com",
                            Partner1Name = "Alice",
                            Partner2Name = "Bob",
                            WeddingDate = new DateTime(2024, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+LogisticsTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogisticsTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Arrange transport for guests",
                            ScheduledTime = new DateTime(2024, 5, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TaskType = "Transportation"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Confirm menu with vendor",
                            ScheduledTime = new DateTime(2024, 5, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "In Progress",
                            TaskType = "Catering"
                        });
                });

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Can we discuss the venue options?",
                            IsRead = false,
                            Receiver = "Planner",
                            Sender = "John & Jane",
                            Timestamp = new DateTime(2024, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Please confirm the catering menu.",
                            IsRead = true,
                            Receiver = "Alice & Bob",
                            Sender = "Planner",
                            Timestamp = new DateTime(2024, 5, 10, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+ReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+VendorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = "Available",
                            Category = "Venue",
                            ContactInfo = "contact@elegantvenues.com",
                            Description = "Beautiful venue for weddings with elegant decor",
                            IsFavorite = false,
                            Location = "New York, NY",
                            Name = "Elegant Venues",
                            Price = 15000m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Availability = "Booked",
                            Category = "Catering",
                            ContactInfo = "contact@tastycatering.com",
                            Description = "Delicious wedding catering with customizable menus",
                            IsFavorite = true,
                            Location = "Los Angeles, CA",
                            Name = "Tasty Catering",
                            Price = 5000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Availability = "Available",
                            Category = "Florist",
                            ContactInfo = "contact@bloomflorist.com",
                            Description = "Stunning floral arrangements for weddings",
                            IsFavorite = false,
                            Location = "Chicago, IL",
                            Name = "Bloom Florist",
                            Price = 2000m,
                            Rating = 4.7999999999999998
                        });
                });

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+WeddingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoupleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weddings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 50000m,
                            CoupleName = "John & Jane",
                            Date = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Colombo 07",
                            Status = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 60000m,
                            CoupleName = "Alice & Bob",
                            Date = new DateTime(2024, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Galle Face",
                            Status = "Planning"
                        });
                });

            modelBuilder.Entity("DreamDays.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMFAEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeddingEventId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@dreamdays.com",
                            IsMFAEnabled = false,
                            Password = "Admin123!",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "planner@dreamdays.com",
                            IsMFAEnabled = false,
                            Password = "Planner123!",
                            Role = "Planner"
                        });
                });

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+ReviewEntity", b =>
                {
                    b.HasOne("DreamDays.Data.DreamDaysDbContext+VendorEntity", null)
                        .WithMany("Reviews")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DreamDays.Data.DreamDaysDbContext+VendorEntity", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
